CREATE TABLE TITULOS(
    CODIGO INTEGER NOT NULL PRIMARY KEY,
    DESCRICAO VARCHAR2(100) NOT NULL
);


CREATE TABLE PROFESSORES (
    CODIGO INTEGER NOT NULL PRIMARY KEY,
    NOME VARCHAR2(500) NOT NULL,
    CPF VARCHAR2(12) NOT NULL UNIQUE,
    TITULACAO_MAXIMA INTEGER NOT NULL,
    CONSTRAINT fk_professor_titulo 
        FOREIGN KEY TITULACAO_MAXIMA
        REFERENCES TITULOS(CODIGO)
);

SELECT P.NOME FROM PROFESSORES P ORDER BY P.NOME;

SELECT P.NOME, T.DESCRICAO
FROM PROFESSORES P
INNER JOIN TITULOS T ON T.CODIGO = P.TITULACAO_MAXIMA
ORDER BY P.NOME ASC